### ISSUE TITLE
More of a comment but 1.17.4 not working when running pub get (using dart 1.18.0)

### ISSUE THREAD

**Issue by ed-snodgrass** [MikeMitterer/dart-material-design-lite-site#2]
Tried using mdl: 1.17.4 in my pubspec.yaml

When running `pub get` i get the following:

> Package mdl has no versions that match 1.17.4 derived from

mdl: 1.17.3 does work fine.

```
name: dartTourOfHeroes
version: 0.0.1
description: Dart Tour of Heroes
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.17
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  http: ^0.11.3+3
  jsonpadding: ^0.1.0
  mdl: 1.17.4
  sqljocky: 0.14.1
  stream_transformers: ^0.3.0+3
transformers:
- angular2:
    platform_directives:
    - package:angular2/common.dart#COMMON_DIRECTIVES
    platform_pipes:
    - package:angular2/common.dart#COMMON_PIPES
    entry_points: web/main.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
- dart_to_js_script_rewriter
```
